### ISSUE TITLE
Sample pitch control and playback speed

### ISSUE THREAD

**Issue by Qualphey** [lsp-plugins/lsp-plugins-sampler#1]
Would it be possible to implement these two? I would contribute myself if you would just give me a few pointers.

**Comment by sadko4u** [comment]
Hello! At this moment LSP has no pitch shifting algorithm implementation.
The playback speed also affects the pitch of the sample without the pitch compensation.
I need more detailed information of how you want to utilize both functionsl

**Comment by Qualphey** [comment]
Thanks for responding! :) Well I'm using LSP multisampler for making drum beats with pads on a midi keyboard/controller and I wanna be able to control the pitch of each sample to make it sound more "in tune" with the rest of the track. Changing the playback speed without pitch compensation would sort of do the trick for now, though does LSP have something like this implemented that could be integrated into the multisampler?

Anyway, an Ideal solution would be playback speed control with pitch compensation and pitch shifting without affecting the playback speed.

I've been looking at `lsp-dsp-lib` and `lsp-dsp-units` and these are probably the modules that I should work on to begin implementing these features, right?

**Comment by sadko4u** [comment]
`lsp-dsp-lib` is a set of low-level functions for optimized processing of data arrays. All functions take arrays as inputs and arrays as outputs. This is pretty good vectorizable and can be optimized with assembly language.
`lsp-dsp-units` is a library of high-level `bricks` that can be used for audio processing. So if you write a module that performs time stretching, this is the main library to aim for. If you're willing to optimize some functions, then `lsp-dsp-lib` is your choice.

**Comment by Qualphey** [comment]
I've also opened pull requests with minor additions for [lsp-plugin-fw](https://github.com/lsp-plugins/lsp-plugin-fw) and [lsp-plugins-shared](https://github.com/lsp-plugins/lsp-plugins-shared) repos. This is a very basic implementation. Adds a knob which allows you to change the sample rate. Please review my pull requests when you can and let me know what you think 'bout them.

I'm also thinking about adding a `duration` knob in the future which would basically stretch the sample by multiplying or cutting out its pieces.

**Comment by Qualphey** [comment]
Let me know, if you need me to add additional information to each pull request describing the changes. :)

**Comment by sadko4u** [comment]
Hello! I had not so much time to perform the review. I'll do it within few days.

**Comment by sadko4u** [comment]
I have looked your PR and have series of questions:
- You have implemented the feature for Multisampler plugin. But what's with single sampler? That also requires to be changed.
- The sample rate control looks for me being not good solution. It is very hard to compute the actual pitch shift when you don't know the original sample rate of the host. So, for different sample rates of the host that will sound different. And that's not good.
- I would like to add the `pitch` control instead of sample rate which can be expressed in semitones. By default, the `0 st` should be set and force the loaded sample to be resampled to the sample rate of the host. Changing the `pitch` should automatically recompute the proper target sample rate and trigger the resampling.
- We can allow to resample in range of +/- 2 octaves and this should be enough. 

So, I think your set of PR requires to be reworked.

**Comment by Qualphey** [comment]
I've reworked my changes based on your comments. :) Still not sure if I got it right, but it is definitely way closer to what your were talking about.

**Comment by sadko4u** [comment]
I have merged changes into the `devel` branch.
The code required set of changes, you can review them in this commit: fb429af28b752e2b287837fd1898381e53c49f96
